/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/ZPT1vN8xutu
 */

import { ChevronsDownIcon } from "lucide-react"


export function frequent() {
  return (
    <>
      <section className="w-full py-12 md:py-24 lg:py-32">
        <div className="container px-4 md:px-6">
          <div className="space-y-6">
            <div className="text-center">
              <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl">Frequently asked questions</h1>
              <p className="text-gray-500 dark:text-gray-400 mt-2">
                Here you can find more details about our services and offerings.
              </p>
            </div>
            <div className="space-y-4">
              <div className="border rounded-lg">
                <button className="flex  items-center justify-between p-4 text-left w-full font-semibold focus:outline-none">
                  How can I change my subscription plan?
                  <span className="ml-auto opacity-50">
                    <ChevronsDownIcon className="w-4 h-4" />
                  </span>
                </button>
                <div className="p-4 border-t text-sm">
                  To change your subscription plan, please log in to your account and navigate to the "Subscription"
                  section. You can then select the new plan you wish to subscribe to and follow the prompts to confirm
                  the changes.
                </div>
              </div>
              <div className="border rounded-lg">
                <button className="flex  items-center justify-between p-4 text-left w-full font-semibold focus:outline-none">
                  Can I cancel my subscription at any time?
                  <span className="ml-auto opacity-50">
                    <ChevronsDownIcon className="w-4 h-4" />
                  </span>
                </button>
                <div className="p-4 border-t text-sm">
                  Yes, you can cancel your subscription at any time. To do so, please visit the "Subscription" section
                  of your account and follow the instructions to cancel your subscription. Once canceled, you will no
                  longer be billed, and your access to premium features will continue until the end of the current
                  billing period.
                </div>
              </div>
              <div className="border rounded-lg">
                <button className="flex  items-center justify-between p-4 text-left w-full font-semibold focus:outline-none">
                  How do I reset my password?
                  <span className="ml-auto opacity-50">
                    <ChevronsDownIcon className="w-4 h-4" />
                  </span>
                </button>
                <div className="p-4 border-t text-sm">
                  If you need to reset your password, you can do so by clicking the "Forgot password" link on the login
                  page. You will then be prompted to enter your email address, and a password reset link will be sent to
                  you. Follow the link to set a new password for your account.
                </div>
              </div>
              <div className="border rounded-lg">
                <button className="flex  items-center justify-between p-4 text-left w-full font-semibold focus:outline-none">
                  What payment methods do you accept?
                  <span className="ml-auto opacity-50">
                    <ChevronsDownIcon className="w-4 h-4" />
                  </span>
                </button>
                <div className="p-4 border-t text-sm">
                  We accept the following payment methods: Visa, Mastercard, American Express, Discover, PayPal, and
                  Apple Pay. You can add or update your payment method in the "Billing" section of your account.
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  )
}



