/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/IkstLL4Umpb
 */
import { Button } from "@/components/ui/button"
import { BriefcaseIcon, LightbulbIcon, ShieldCheckIcon } from "lucide-react"

export function subs() {
  return (
    <div className="bg-[#F8F9FA] py-20">
      <div className="max-w-6xl mx-auto px-4">
        <h1 className="text-5xl font-bold text-center mb-6">Subscription Plan</h1>
        <p className="text-center text-lg mb-16">
          In publishing and graphic design, Lorem ipsum is a placeholder text commonly
        </p>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          <div className="bg-white rounded-lg p-8 shadow-lg flex flex-col items-center">
            <ShieldCheckIcon className="text-[#FFA500] mb-4 text-3xl" />
            <h2 className="text-2xl font-bold mb-4">Basic</h2>
            <p className="text-center mb-4">Ideal to Discover Amazon Sellers market get Started with outreach</p>
            <p className="mb-4">250 Leads</p>
            <p className="mb-6">Monthly: $190/month ($0.76 per lead)</p>
            <div className="text-3xl font-bold text-[#FFA500] mb-2">$1940</div>
            <div className="text-sm line-through text-gray-500 mb-6">$2280</div>
            <Button className="bg-[#FFA500] text-white">Purchase</Button>
          </div>
          <div className="bg-white rounded-lg p-8 shadow-xl flex flex-col items-center border-4 border-[#6C63FF]">
            <LightbulbIcon className="text-[#6C63FF] mb-4 text-3xl" />
            <h2 className="text-2xl font-bold mb-4">Advanced</h2>
            <p className="text-center mb-4">
              Ideal to ramp up outreach to Amazon Seller Contacts for a single salesperson
            </p>
            <p className="mb-4">500 Leads</p>
            <p className="mb-6">Monthly: $350/month ($0.7 per lead)</p>
            <div className="text-3xl font-bold text-[#6C63FF] mb-2">$3570</div>
            <div className="text-sm line-through text-gray-500 mb-6">$4200</div>
            <Button className="bg-[#6C63FF] text-white">Purchase</Button>
          </div>
          <div className="bg-white rounded-lg p-8 shadow-lg flex flex-col items-center">
            <BriefcaseIcon className="text-[#00BFFF] mb-4 text-3xl" />
            <h2 className="text-2xl font-bold mb-4">Premium</h2>
            <p className="text-center mb-4">
              Ideal for the mid-to-large sales team that wants to scale Up their outreach to e-commerce Sellers
            </p>
            <p className="mb-4">1000 Leads</p>
            <p className="mb-6">Monthly: $650/month ($0.65 per lead)</p>
            <div className="text-3xl font-bold text-[#00BFFF] mb-2">$6630</div>
            <div className="text-sm line-through text-gray-500 mb-6">$7900</div>
            <Button className="bg-[#00BFFF] text-white">Purchase</Button>
          </div>
        </div>
      </div>
    </div>
  )
}

