/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/NRX8getPDLc
 */
import Link from "next/link"

export default function UILan() {
  return (
    <section className="w-full py-3 md:py-6  dark:border-white-800">
      <div className="container px-8 md:px-16">
        <div className="flex flex-col items-center justify-center space-y-3 text-center">
          <div className="space-y-2">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl text-white">We support 80+ languages</h2>
            <p className="max-w-[500px] text-white inline-flex items-center justify-center md:text-lg/relaxed lg:text-base/relaxed xl:text-lg/relaxed dark:text-white">
              Write code in any language you want, be it C, C++, Java, Python, JavaScript, SQL, etc. We are here to
              help.
            </p>
          </div>
          <Link
            className="inline-flex h-10 items-center rounded-md bg-blue-950 px-8 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-blue-800 dark:hover:bg-gray-50/90 dark:focus-visible:ring-blue-300"
            href="#"
          >
            Get Started
          </Link>
        </div>
      </div>
    </section>
  )
}
