/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/YI62x1Hi81B
 */
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"
import Link from "next/link"

export function InputForm() {
  return (
    <div key="1" className="">
      <div className="">
        <div
          className=" bg-white rounded-md shadow p-6"
          style={{
            width: "32rem",
          }}
        >
          <h1 className="text-2xl font-semibold mb-6">Create a new schema</h1>
          <form>
            <div className="mb-4">
              <label className="block text-sm font-medium mb-1" htmlFor="prompt">
                Prompt
              </label>
              <Input id="prompt" placeholder="Describe the data you want to generate" />
            </div>
            <div className="mb-4">
              <label className="block text-sm font-medium mb-1" htmlFor="negative-prompt">
                Negative Prompt
              </label>
              <Input id="negative-prompt" placeholder="A prompt that describes what to avoid " />
            </div>
            <div className="mb-4">
              <label className="block text-sm font-medium mb-1" htmlFor="data-sources">
                Data Sources
              </label>
              <Input id="data-sources" placeholder="Table names (Comma separated)" />
            </div>
            <div className="mb-4">
              <label className="block text-sm font-medium mb-1" htmlFor="input-schema">
                Input Schema
              </label>
              <Textarea id="input-schema" placeholder="Input schema" />
            </div>
            <div className="mb-4">
              <label className="block text-sm font-medium mb-1" htmlFor="Output-schema">
                Output Schema
              </label>
              <Textarea id="output-schema" placeholder="Output schema" />
            </div>
            <div className="flex justify-end mt-4">
            <Link href='/dashboard'>
            <Button >Generate</Button>
            </Link>
              
            </div>
          </form>
        </div>
      </div>
    </div>
  )
}
